### ISSUE TITLE
100% test coverage of MDMPerformerGroup

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-runtime-objc#25]
Latest coverage results as of 3b1ddbad729d73879fde243648c02c8b6f747d82:

```
52%     src/private/MDMPerformerGroup.m
```

Untested methods:
- `- (void)setUpFeaturesForPerformerInfo:(MDMPerformerInfo *)performerInfo` delegated performance.
- `- (id<MDMPerforming>)performerForPlan:(id<MDMPlan>)plan` for a plan being registered to an existing performer.

**Comment by willlarche** [comment]
For performerForPlan case:
Performer object needs to implement delegated performer methods.
