### ISSUE TITLE
Facebook POP Family

### ISSUE THREAD

**Issue by willlarche** [material-motion/material-motion-runtime-objc#40]
Facebook POP SDK support.

May be similar to CoreAnimation family. 

Make POP objects conform to MDMPlan?

**Comment by willlarche** [comment]
Write in Swift first.

**Comment by maxluzuriaga** [comment]
https://github.com/material-motion/material-motion-family-pop-swift Working on this here

**Comment by maxluzuriaga** [comment]
http://codereview.cc/D1433 Diff for the initial implementation + example!
