### ISSUE TITLE
Create a unit test that assert that named plans overwrite previously named plans

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion-runtime-objc#81]
Example pseudo-code:

```
transaction.add(plan: PlanA, to: target, withName: "plan")
transaction.add(plan: PlanB, to: target, withName: "plan")
```

Should result in PlanA being added, removed, and then PlanB being added.

**Comment by seanoshea** [comment]
Was looking into taking a crack at this yesterday evening. Had a look at`MDCTransaction`:

```
NS_SWIFT_NAME(Transaction)
@interface MDMTransaction : NSObject

#pragma mark Adding plans to a transaction

/** Associate an plan with a given target. */
- (void)addPlan:(nonnull id<MDMPlan>)plan
       toTarget:(nonnull id)target
    NS_SWIFT_NAME(add(plan:to:));

@end
```

Would tackling this issue also include adding another method to `MDCTransaction` which would look something like https://github.com/material-motion/material-motion-runtime-android/blob/develop/library/src/main/java/com/google/android/material/motion/runtime/Transaction.java#L60 ?

**Comment by jverkoey** [comment]
Yep! We've got this listed in https://github.com/material-motion/material-motion-runtime-objc/issues/8, which if we could mark it as such would be a blocking issue on this one.

**Comment by jverkoey** [comment]
https://github.com/material-motion/material-motion-runtime-objc/issues/79 is a blocking issue as well.

**Comment by jverkoey** [comment]
The Named plans MVP has the ordered list of tasks: https://github.com/material-motion/material-motion-runtime-objc/milestone/4

**Comment by jverkoey** [comment]
And the spec: https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/runtime/named-plans.html

**Comment by seanoshea** [comment]
Closing this out as https://github.com/material-motion/material-motion-runtime-objc/pull/88 has been merged in.
